name: teste-integracao-kafka

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      kafka:
        image: spotify/kafka
        env:
          ADVERTISED_PORT: 9092
        ports:
          - 9092:9092
          - 2181:2181

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Teste envio mensagens
        run: |
          cd ./EnvioKafka
          sudo dotnet run "kafka:9092" "topic-teste" "1" "2" "tres" "quartro"
      - name: Run a multi-line script
        run: |
          cd ./Ambiente
          docker-compose ps
      - name: Run a multi-line script
        run:
          docker container ls
